const {
  AWS_ACCES_KEY_ID,
  AWS_SECRET_KEY,
  AWS_BUCKET_VISUALIZATION_SCREEN_SHOTS,
  FE_URL,
  API_URL,
  CRAWLER_PORT,
  CRAWLER_WIDTH,
  CRAWLER_HEIGHT,
  CRAWLER_DEVICE_SCALE,
} = process.env;
export const Env = {
  AWS_ACCES_KEY_ID,
  AWS_SECRET_KEY,
  AWS_BUCKET_VISUALIZATION_SCREEN_SHOTS,
  FE_URL,
  API_URL,
  CRAWLER_PORT: parseInt(CRAWLER_PORT, 10),
  CRAWLER_WIDTH: parseInt(CRAWLER_WIDTH, 10),
  CRAWLER_HEIGHT: parseInt(CRAWLER_HEIGHT, 10),
  CRAWLER_DEVICE_SCALE: parseInt(CRAWLER_DEVICE_SCALE, 10),
};
