enum colors {
  navy = 'navy',
  red = 'red',
  yellow = 'yellow',
  purple = 'purple',
  orange = 'orange',
  green = 'green',
  pink = 'pink',
  cyan = 'cyan',
  blue = 'blue',
  brown = 'brown',
  magenta = 'magenta',
  maroon = 'maroon',
  lime = 'lime',
  teal = 'teal',
  olive = 'olive',
  apricot = 'apricot',
  levander = 'levander',
  mint = 'mint',
  beige = 'beige',
  black = 'black'
}

export const COLOR_CODES: { [key: string]: string } = {
  [colors.navy]: '#000075',
  [colors.red]: '#e6194B',
  [colors.yellow]: '#ffe119',
  [colors.purple]: '#911eb4',
  [colors.orange]: '#f58231',
  [colors.green]: '#3cb44b',
  [colors.pink]: '#fabebe',
  [colors.cyan]: '#42d4f4',
  [colors.blue]: '#4363d8',
  [colors.brown]: '#9A6324',
  [colors.magenta]: '#f032e6',
  [colors.maroon]: '#800000',
  [colors.lime]: '#bfef45',
  [colors.teal]: '#469990',
  [colors.olive]: '#808000',
  [colors.apricot]: '#ffd8b1',
  [colors.levander]: '#e6beff',
  [colors.mint]: '#aaffc3',
  [colors.beige]: '#fffac8',
  [colors.black]: '#000000'
};
